title:              HEDA
email:              your-email@example.com
description:        함께 머리를 맞대어 솔루션을 만들어나가는 데이터 분석가들의 모임입니다. 우리는 점이지만 서로 이어진다면 선과 면, 그리고 공간이 됩니다. 헤다와 함께 입체적인 솔루션을 만들어보세요.
author:             Start Bootstrap
baseurl:            "/data-heda"
url:                "https://data-heda.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
